### PR TITLE
Create mixed-methods.md

### PR DESCRIPTION
**Pull request by elizaroliveira**
I'm at the beggining of my text. :)

### CODE REVIEW

**Comment by fominykh** [comment]
this is a nice draft

**Review by lprisan — COMMENTED** [review]
Sorry, I'm missing a bit the context of this: initially I thought it was going to be a chapter for the book, on the topic of mixed methods. But it seems like a piece copied from some thesis?
Is this just a test?

**Comment by elizaroliveira** [comment]
Hi Iprisan, Mikhail was teaching me how to use github. It was a workshop at the University of Aveiro. I need to start all over. 
It will be indeed a chapter, regarding mixed methods, for the book. Just put a part of my thesis to visualize how the text appears on github. Sorry. I'll add some stuff after Christmas. Is that ok? :)

Thank you for your attention.

**Comment by lprisan** [comment]
Heheheh, I guessed it was something like that. Sure, whenever you're ready to contribute, you're welcome! 🙂
________________________________

**Pull request closed without merging**
